### ISSUE TITLE
Ensuring equal representation from under represented groups

### ISSUE THREAD

**Issue by joesepi** [nodejs/bootstrap#106] opened 2019-02-19 19:29 UTC
As mentioned in a previous CommComm meeting and raised again in the comments of the Joint Town Hall on Feb 19:

>Jake Niemiec​: Question, In the node.js Jan 25, 2019 51:22 Comm Comm meeting, Michal D and Dan S indicated that gender identity and race would be a factor in membership. Is this still a goal?

Is equal representation in membership a goal and if so, what ways can we ensure that goal be met?

**Comment by jakeNiemiec** [comment] 2019-02-19 19:46
Thanks for taking my question, here is the link to that meeting: https://youtu.be/MkNz0Ed2r8c?t=3081

I don't have a strong opinion, I would just like to see representation goals clearly defined (as opposed to a `member` making a personal judgment call). This way, if you need to reject someone based on their gender identity or race, the `member` can point to the codified targets and that someone  would take it less personally.

**Comment by MylesBorins** [comment] 2019-02-19 19:57
@jakeNiemiec while our community has aspirations for increasing diversity from underrepresented groups (race, gender, creed, religion, or any other protected category), these will never be used as factors to exclude anyone from participation. To be explicit, there will never be quotas.

Is this a sufficient answer to close this issue?

**Comment by jakeNiemiec** [comment] 2019-02-19 21:10
Thanks for your response, let me detail what causes me to bring this up. 

This harkens back to @bnb limiting discussion on this topic back here: https://github.com/nodejs/community-committee/issues/260#issuecomment-379547438

>I'd like to suggest we cut this discussion a bit short and discuss it _at the Collaborator's Summit_....this was one of the things that caused some major issues and eventually led to the WG being shuttered.

 https://github.com/nodejs/summit/issues/75#issuecomment-393525992 In the Collaborator's Summit meeting@10:24 @tiriel speaks out against _"positive discrimination"_. @10:41 Tracy asks _"Would you like me to explain why people do practice positive discrimination"_. They go on to say _"The reason is that we specifically, and very vocally seek out underrepresented groups to come participate, is **because they have been programmed by their upbringing** that just because someone says you are welcome, the 'you' tends to be 'not them'..."_. They go on to explain how CommComm fixed some of the "buy-in" issues that the inclusivity WG had (19:50, 27:40). **I have no issue with the program Tracy discussed, just the way it was discussed**.

After that and when they talk about extracting money from the board, there is discussion on adopting "Globe Smart". The [meeting notes say](https://docs.google.com/document/d/1FV8X0xghtFDqwTho6GtsUHeH3uTzY8bmWVP8WGEFkyI/edit):

>Globe Smart identifies possible problems and frictions coming from cultural differences by asking people to answer a set of questions

I think this is not a good idea, no one should have to "take a test" to see if their culture is valid to join the foundation. I don't want to see this kind of American-centric cultural imperialism, **no one should be judged based on where they come from or what their culture is like**.

@MylesBorins, you may not have quotas (probably not legal anyway), but there seems to be a pattern of behavior & intention. This does not include info from my private inquiries to CC & TSC members.

**This shouldn't be a big deal**, I just want to see the new foundation say goodbye to practices that discriminate.

**Comment by Tiriel** [comment] 2019-02-19 22:01
Hey there!

Since I've been summoned in this thread, I'd like to say a few words.
Most importantly: **please do not take bits of discussions on another (although related) subject out of context**.

My reaction there was precisely caused by a cultural difference between my own country (France) and North-American (I think, but do apologize if I'm wrong) culture. This was not some white-dude whining against inclusive strategies but on the contrary, an attempt to raise a flag against a strategy I thought might lead to quotas and still under-representation of some groups. The idea was never to say that we should be wary of recruiting less white males.

Hence, I am deeply uneasy about my reaction being quoted here to make a case against possible discrimination toward white males.

I regard to the original question, I think @MylesBorins 's answer is perfectly satisfying, and that @dshaw 's citation must be observed in its entirety. There was never an intent to discriminate against anyone. There was on the other hand and intent to not have **just** one gender/ethnic identity, and so to reach out to under-represented groups to include them **also**.

At least that's what I understand from the meetings and from my time in the CommComm.
If I'm overstepping, please feel free to edit/delete my comment or request that I do so myself. Please do remember that English is not my first language (and that my country is terrible at teaching it).

**Comment by MylesBorins** [comment] 2019-02-19 22:13
@jakeNiemiec if you believe individuals from the foundation are acting in a way that is not inline with our code of conduct please follow the steps outlined in [or moderation guidelines](https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#requesting-moderation) e.g. sending an email to report@nodejs.org

I believe I've answered the content of the initial question and politely request that this issue be closed and concerns about conduct go through official channels.

**Comment by jakeNiemiec** [comment] 2019-02-19 22:28
>My reaction there was precisely caused by a cultural difference between my own country (France) and North-American (I think, but do apologize if I'm wrong) culture.

@Tiriel Inclusive strategies are great, excluding people based on personal attributes or the culture they come from is bad. Most North-Americans would agree with that. You said it best [here](https://github.com/nodejs/community-committee/issues/260#issuecomment-379307047)

> I don't care who or what you are, or where you come from on a physical, metaphysical or social level. I don't care who you love or don't love, what are your political and religious beliefs or lack thereof. You are deeply and equally welcome here, as long as you're willing to share some things with us in peace and openness.

I would like this for the new foundation. @MylesBorins, I don't want to report anyone, I want to **discuss** how the new foundation can avoid these divisive pitfalls. Would you be willing to have this discussion?

**Comment by Tiriel** [comment] 2019-02-19 22:39
@jakeNiemiec Again, I not in favour of including these kinds of quotes in here to justify some other parts I don't condone. Plainly, I don't think there was any discrimination against white males in everything you quoted from the bootstrap meeting, and the other answers seemed fully satisfying in that regard.

Plus, I'd like you to please edit your post to remove this quote. I said this and stand by it, but this is taken out of context. I lacked some context too at that time, otherwise, I would have formulated another way.

I do appreciate your concerns on the topic of inclusivity/diversity though, it's an important topic in my opinion.

**Comment by jakeNiemiec** [comment] 2019-02-19 22:58
It's a sad state of affairs when "you are deeply welcome here" is a statement that needs to be removed.

@MylesBorins, feel free to close or even remove. I see now that my point of view is unwelcome. Good luck on the merger.

**Comment by bnb** [comment] 2019-02-19 23:24
Going to close this, since the original question was answered.

**Closed by bnb** 2019-02-19 23:24 UTC
